-- =============================================================================
-- DEPRECATED — DO NOT USE AS PRODUCTION SCHEMA SOURCE
--
-- As of June 2026, Alembic migrations (alembic/versions/) are the sole
-- source of truth for the production database schema.  This file is kept
-- for reference only.  All tables are now created and evolved exclusively
-- through Alembic:
--
--   Migration 0000: gateway_jobs, workspaces, job_events, approvals
--   Migration 0001: runners, runner_observations, workspace_observations,
--                   opencode_instance_observations
--   Migration 0002: webhooks
--   Migration 0003: gateway_jobs.env_vars
--   Migration 0004: gateway_jobs (branch_name, mr_url, workflow_run_id)
--   Migration 0005: gateway_jobs indexes
--   Migration 0006: runner_events
--   Migration 0007: runners (admin_status, health_status)
--   Migration 0008: workspaces cleanup timestamp columns
--   Migration 0009: workspaces port CHECK constraint
--   Migration 0010: gateway_jobs (commit_sha, failure_reason)
--
-- The SQL DDL below is commented out.  It is retained solely as a static
-- reference snapshot of the original schema.sql era and may be removed in
-- a future release.
-- =============================================================================

-- The following statements are retained for reference only.
-- They are NOT executed — Alembic is the authoritative schema owner.

-- CREATE TABLE IF NOT EXISTS gateway_jobs (
--     id              UUID PRIMARY KEY,
--     status          TEXT NOT NULL,
--     repo_url        TEXT NOT NULL,
--     task_summary    TEXT NOT NULL,
--     runner_id       UUID,
--     workspace_name  TEXT,
--     opencode_url    TEXT,
--     opencode_session_id TEXT,
--     executor_type   TEXT NOT NULL,
--     executor_job_id TEXT,
--     env_vars        JSONB DEFAULT '{}'::jsonb,
--     branch_name     TEXT,
--     mr_url          TEXT,
--     workflow_run_id TEXT,
--     created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     completed_at    TIMESTAMPTZ,
--     diff            TEXT
-- );

-- ALTER TABLE gateway_jobs ADD COLUMN IF NOT EXISTS diff TEXT;
-- ALTER TABLE gateway_jobs ADD COLUMN IF NOT EXISTS branch_name TEXT;
-- ALTER TABLE gateway_jobs ADD COLUMN IF NOT EXISTS commit_sha TEXT;
-- ALTER TABLE gateway_jobs ADD COLUMN IF NOT EXISTS mr_url TEXT;
-- ALTER TABLE gateway_jobs ADD COLUMN IF NOT EXISTS workflow_run_id TEXT;
-- ALTER TABLE gateway_jobs ADD COLUMN IF NOT EXISTS failure_reason TEXT;

-- CREATE TABLE IF NOT EXISTS approvals (
--     id              UUID PRIMARY KEY,
--     job_id          UUID NOT NULL REFERENCES gateway_jobs(id),
--     requested_by    TEXT NOT NULL,
--     requested_action TEXT NOT NULL,
--     approval_type   TEXT NOT NULL,
--     approved_by     TEXT,
--     status          TEXT NOT NULL,
--     created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     decided_at      TIMESTAMPTZ
-- );

-- CREATE TABLE IF NOT EXISTS workspaces (
--     id              UUID PRIMARY KEY,
--     runner_id       UUID,
--     workspace_name  TEXT NOT NULL,
--     path            TEXT NOT NULL,
--     repo_url        TEXT NOT NULL,
--     branch          TEXT,
--     port            INTEGER CHECK (port IS NULL OR (port >= 10000 AND port <= 10999)),
--     service_name    TEXT,
--     pinned          BOOLEAN NOT NULL DEFAULT FALSE,
--     cleanup_after   TIMESTAMPTZ,
--     cleanup_status  TEXT NOT NULL DEFAULT 'active',
--     created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );

-- CREATE TABLE IF NOT EXISTS job_events (
--     id              UUID PRIMARY KEY,
--     job_id          UUID NOT NULL REFERENCES gateway_jobs(id),
--     event_type      TEXT NOT NULL,
--     actor           TEXT NOT NULL,
--     details         TEXT,
--     previous_status TEXT,
--     created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );

-- CREATE TABLE IF NOT EXISTS webhooks (
--     id              UUID PRIMARY KEY,
--     url             TEXT NOT NULL,
--     events          TEXT[] NOT NULL DEFAULT '{}',
--     secret          TEXT NOT NULL,
--     created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
